[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/followup"
  to = "/.netlify/functions/followup"
  status = 200

[[redirects]]
  from = "/api/ai/followup"
  to = "/.netlify/functions/followup"
  status = 200

[[redirects]]
  from = "/api/ai/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/send-contact-email"
  to = "/.netlify/functions/send-contact-email"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# netlify.toml
[dev]
  # this tells Netlify Dev to look for your Vite app on 8080 instead of 5173
  targetPort = 8080
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"

 Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data:; connect-src 'self' https://api.slashexperiences.in https://ceqpdprcqhmkqdbgmmkn.supabase.co https://maps.googleapis.com http://localhost:8000 https://maps.gstatic.com https://api.mapbox.com https://events.mapbox.com https://api.openai.com https://slash-rag-agent.onrender.com https://nominatim.openstreetmap.org;" 

